################################################################################
#
# Exploration: Historical NEM Data (OpenNEM)
#
# Examines historical generation, energy, and market data retrieved from
# the OpenNEM API via the opennemr package. Creates charts analogous to the
# ISP Shiny app (energy by year, technology, and region) to understand the
# data structure and assess Shiny integration options.
#
# Ryan Batchelor
# March 2026
#
################################################################################


# ===== Setup ==================================================================

source("setup.r")
source("processing/00-utils.R")
source("R/technology-crosswalk.R")

# Load historical data (generated by processing/03-process-historical-data.R)
load("shiny-webtool/data/nem_historical_network_data.rda")
load("shiny-webtool/data/nem_historical_market_data.rda")


# ===== Fueltech lookup table ==================================================
#
# Maps OpenNEM fueltech codes to display labels, colours, and technology type.
# Colours are aligned with util_table where ISP and OpenNEM categories match.

fueltech_lookup <- tribble(
  ~fueltech,             ~label,                    ~colour,    ~tech_type,       ~order,
  "coal_black",          "black coal",              "#373A36",  "coal",           1,
  "coal_brown",          "brown coal",              "#94795D",  "coal",           2,
  "gas_ccgt",            "gas (CCGT)",              "#008578",  "gas",            3,
  "gas_steam",           "gas (steam)",             "#40C1AC",  "gas",            4,
  "gas_ocgt",            "gas (OCGT)",              "#3FB9C4",  "gas",            5,
  "gas_recip",           "gas (recip.)",            "#00594F",  "gas",            6,
  "gas_wcmg",            "gas (WCMG)",              "#0E6659",  "gas",            7,
  "distillate",          "distillate",              "#FF6666",  "gas",            8,
  "bioenergy_biomass",   "biomass",                 "#B38210",  "renewable",      9,
  "hydro",               "hydro",                   "#A4DBE8",  "renewable",      10,
  "wind",                "wind",                    "#A1D884",  "renewable",      11,
  "solar_utility",       "utility-scale solar",     "#FDD26E",  "renewable",      12,
  "solar_rooftop",       "rooftop solar",           "#F8E08E",  "renewable",      13,
  "battery_discharging", "battery (discharge)",     "#77C5D5",  "storage",        14,
  "pumps",               "pumped hydro (load)",     "#606EB2",  "storage_load",   15,
  "battery_charging",    "battery (charge)",        "#A3519B",  "storage_load",   16,
  "battery",             "battery (net)",           "#77C5D5",  "storage",        17
)


# ===== Helper: period and financial year columns ==============================
#
# period_start is POSIXct in AEST (Etc/GMT-10), marking the first moment of
# the monthly period (e.g. 2009-07-01 = July 2009).
#
# Adds:
#   period_end     – last second of the same calendar month (AEST)
#   month          – calendar month integer (1–12)
#   year           – calendar year integer
#   year_month     – "YYYY-MM" label for the period
#   financial_year – Australian FY ending June; July–Dec map to FY = year + 1,
#                    Jan–June map to FY = year  (e.g. Jul 2009 → FY2010)

add_period_columns <- function(df) {
  df |>
    mutate(
      period_end     = ceiling_date(period_start + seconds(1), "month") - seconds(1),
      month          = month(period_start),
      year           = year(period_start),
      year_month     = format(period_start, "%Y-%m"),
      financial_year = if_else(month >= 7L, year + 1L, year)
    )
}


# ===== Prepare energy data ====================================================

energy_data <- nem_historical_network_data |>
  filter(metric == "energy") |>
  add_period_columns() |>
  left_join(fueltech_lookup, by = "fueltech") |>
  mutate(
    value_gwh = value / 1000,           # MWh → GWh
    region = str_remove(network_region, "1$")  # NSW1 → NSW
  )

# Annual NEM-wide energy by fueltech
energy_annual_nem <- energy_data |>
  filter(!is.na(label)) |>
  group_by(financial_year, fueltech, label, colour, tech_type, order) |>
  summarise(value_gwh = sum(value_gwh), .groups = "drop") |>
  mutate(
    label = factor(label, levels = fueltech_lookup$label),
    value_twh = value_gwh / 1000
  )

# Annual energy by fueltech and region
energy_annual_region <- energy_data |>
  filter(!is.na(label)) |>
  group_by(financial_year, region, fueltech, label, colour, tech_type, order) |>
  summarise(value_gwh = sum(value_gwh), .groups = "drop") |>
  mutate(label = factor(label, levels = fueltech_lookup$label))


# ===== Prepare emissions data =================================================

emissions_data <- nem_historical_network_data |>
  filter(metric == "emissions") |>
  add_period_columns() |>
  left_join(fueltech_lookup, by = "fueltech") |>
  mutate(
    value_mt = value / 1e6,             # t → Mt CO2-e
    region = str_remove(network_region, "1$")
  )

emissions_annual_nem <- emissions_data |>
  filter(!is.na(label)) |>
  group_by(financial_year, fueltech, label, colour, tech_type) |>
  summarise(value_mt = sum(value_mt), .groups = "drop") |>
  mutate(label = factor(label, levels = fueltech_lookup$label))


# ===== Prepare market data ====================================================

price_data <- nem_historical_market_data |>
  filter(metric == "price") |>
  add_period_columns() |>
  mutate(region = str_remove(network_region, "1$"))

# Annual volume-weighted average price (use demand as weights via demand sums)
# Simple average per year per region (monthly observations)
price_annual <- price_data |>
  group_by(financial_year, region) |>
  summarise(avg_price = mean(value, na.rm = TRUE), .groups = "drop")


# ===== Chart theme ============================================================

theme_historical <- function() {
  theme_minimal() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_line(color = "gray90", linewidth = 0.15),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.background = element_rect(fill = "white", colour = NA),
      plot.background  = element_rect(fill = "white", colour = NA),
      axis.text.x = element_text(angle = 45, vjust = 1.2, hjust = 1),
      legend.position = "right"
    )
}


# ===== Chart 1: NEM energy by fueltech (TWh) ==================================

p_energy_nem <- energy_annual_nem |>
  filter(tech_type %in% c("coal", "gas", "renewable", "storage")) |>
  ggplot() +
  geom_bar(
    aes(x = financial_year,
        y = value_twh,
        fill = reorder(label, -order)),
    position = "stack",
    stat = "identity"
  ) +
  scale_fill_manual(
    values = setNames(fueltech_lookup$colour, fueltech_lookup$label)
  ) +
  scale_x_continuous(breaks = seq(2010, 2025, by = 2)) +
  scale_y_continuous(labels = label_comma()) +
  labs(
    title = "NEM electricity generation by technology",
    subtitle = "Historical actual (financial year ending June)",
    caption = "Source: OpenNEM",
    x = "Financial year ending June",
    y = "Energy (TWh)",
    fill = "Technology"
  ) +
  theme_historical()

p_energy_nem


# ===== Chart 2: NEM energy by fueltech – stacked area =========================
#
# Area chart shows evolution of the generation mix more clearly

p_energy_area <- energy_annual_nem |>
  filter(tech_type %in% c("coal", "gas", "renewable", "storage")) |>
  ggplot() +
  geom_area(
    aes(x = financial_year,
        y = value_twh,
        fill = reorder(label, -order)),
    position = "stack"
  ) +
  scale_fill_manual(
    values = setNames(fueltech_lookup$colour, fueltech_lookup$label)
  ) +
  scale_x_continuous(breaks = seq(2010, 2025, by = 2)) +
  scale_y_continuous(labels = label_comma()) +
  labs(
    title = "NEM electricity generation mix (area)",
    subtitle = "Historical actual",
    caption = "Source: OpenNEM",
    x = "Financial year ending June",
    y = "Energy (TWh)",
    fill = "Technology"
  ) +
  theme_historical()

p_energy_area


# ===== Chart 3: Renewable share over time =====================================

renewable_share <- energy_annual_nem |>
  group_by(financial_year) |>
  summarise(
    total_twh     = sum(value_twh[tech_type %in% c("coal", "gas", "renewable")]),
    renewable_twh = sum(value_twh[tech_type == "renewable"]),
    .groups = "drop"
  ) |>
  mutate(re_share_pct = renewable_twh / total_twh * 100)

p_re_share <- renewable_share |>
  ggplot(aes(x = financial_year, y = re_share_pct)) +
  geom_line(colour = "#A1D884", linewidth = 1.2) +
  geom_point(colour = "#A1D884", size = 2.5) +
  scale_x_continuous(breaks = seq(2010, 2025, by = 2)) +
  scale_y_continuous(labels = label_percent(scale = 1), limits = c(0, NA)) +
  labs(
    title = "Renewable share of NEM generation",
    subtitle = "% of total generation (excl. storage flows)",
    caption = "Source: OpenNEM",
    x = "Financial year ending June",
    y = "Renewable share (%)"
  ) +
  theme_historical() +
  theme(legend.position = "none")

p_re_share


# ===== Chart 4: Energy by region (faceted) ====================================

p_energy_region <- energy_annual_region |>
  filter(tech_type %in% c("coal", "gas", "renewable", "storage")) |>
  ggplot() +
  geom_bar(
    aes(x = financial_year,
        y = value_gwh / 1000,
        fill = reorder(label, -order)),
    position = "stack",
    stat = "identity"
  ) +
  scale_fill_manual(
    values = setNames(fueltech_lookup$colour, fueltech_lookup$label)
  ) +
  scale_x_continuous(breaks = seq(2010, 2025, by = 5)) +
  scale_y_continuous(labels = label_comma()) +
  facet_wrap(~region, scales = "free_y") +
  labs(
    title = "Electricity generation by region and technology",
    subtitle = "Historical actual (financial year ending June)",
    caption = "Source: OpenNEM",
    x = "Financial year ending June",
    y = "Energy (TWh)",
    fill = "Technology"
  ) +
  theme_historical() +
  theme(strip.text = element_text(face = "bold"))

p_energy_region


# ===== Chart 5: NEM emissions by fueltech =====================================

p_emissions <- emissions_annual_nem |>
  filter(tech_type %in% c("coal", "gas")) |>
  ggplot() +
  geom_bar(
    aes(x = financial_year,
        y = value_mt,
        fill = reorder(label, -as.numeric(label))),
    position = "stack",
    stat = "identity"
  ) +
  scale_fill_manual(
    values = setNames(fueltech_lookup$colour, fueltech_lookup$label)
  ) +
  scale_x_continuous(breaks = seq(2010, 2025, by = 2)) +
  scale_y_continuous(labels = label_comma()) +
  labs(
    title = "NEM electricity sector emissions",
    subtitle = "Historical actual (financial year ending June)",
    caption = "Source: OpenNEM",
    x = "Financial year ending June",
    y = "Emissions (Mt CO2-e)",
    fill = "Technology"
  ) +
  theme_historical()

p_emissions


# ===== Chart 6: Wholesale electricity price by region =========================

region_colours <- c(
  "NSW" = "#1F78B4",
  "QLD" = "#E31A1C",
  "SA"  = "#FF7F00",
  "TAS" = "#33A02C",
  "VIC" = "#6A3D9A"
)

p_price <- price_annual |>
  mutate(region = str_remove(region, "1$")) |>
  ggplot(aes(x = financial_year, y = avg_price, colour = region, group = region)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_colour_manual(values = region_colours) +
  scale_x_continuous(breaks = seq(2010, 2025, by = 2)) +
  scale_y_continuous(labels = label_dollar()) +
  labs(
    title = "NEM wholesale electricity price",
    subtitle = "Monthly average per financial year (simple average)",
    caption = "Source: OpenNEM",
    x = "Financial year ending June",
    y = "Average price ($/MWh)",
    colour = "Region"
  ) +
  theme_historical()

p_price


# ===== Chart 7: Combine energy + renewable share (patchwork) ==================

p_combined <- p_energy_nem / p_re_share +
  plot_layout(heights = c(3, 1)) +
  plot_annotation(
    title = "NEM generation mix and renewable share",
    caption = "Source: OpenNEM"
  )

p_combined


# ===== Chart 8: Combined historical actuals + ISP 2026 projection =============
#
# Historical (OpenNEM): FY2010–FY2025, NEM-wide (sum of all regions)
# Projected (ISP 2026 draft): Step Change ODP (cdp4), FY2027–FY2050, NEM-wide
# Note: FY2026 not present in either dataset – gap is left blank intentionally.
#
# Technologies are aligned to ISP names via a crosswalk so both halves share
# the same fill colours from util_table.

load("shiny-webtool/data/isp_generation_output.rda")

# ----- Historical leg: FY2010–FY2025, coerced to ISP 2026 canonical names ---
#
# add_coerced_tech_cat(col = "fueltech") maps OpenNEM codes → ISP 2026 names.
# Storage-load fueltechs (battery_charging, pumps) map to "utility-scale storage
# load" which we then exclude — keeping only generation, not consumption.

hist_leg <- energy_data |>
  filter(financial_year >= 2010, financial_year <= 2025) |>
  add_coerced_tech_cat(col = "fueltech") |>
  filter(!str_detect(coerced_tech_cat, "load")) |>
  group_by(financial_year, coerced_tech_cat) |>
  summarise(value_gwh = sum(value_gwh), .groups = "drop") |>
  mutate(data_source = "historical")

# ----- ISP leg: FY2027–FY2050, step change ODP (cdp4), NEM-wide sum ---------
#
# add_coerced_tech_cat(col = "technology") maps ISP 2026 names to themselves
# (self-mapping), so coerced_tech_cat == technology for 2026 draft data.
# Older ISP version names would also be correctly coerced if included.

isp_leg <- isp_generation_output |>
  filter(
    source   == "2026_draft",
    scenario == "step change",
    cdp      == "cdp4"
  ) |>
  add_coerced_tech_cat(col = "technology") |>
  filter(!str_detect(coerced_tech_cat, "load")) |>
  group_by(financial_year = year, coerced_tech_cat) |>
  summarise(value_gwh = sum(value), .groups = "drop") |>
  mutate(data_source = "projected")

# ----- Combine and join colours from util_table ------------------------------

combined_energy <- bind_rows(hist_leg, isp_leg) |>
  mutate(
    coerced_tech_cat = factor(coerced_tech_cat, levels = util_table$technology),
    data_source      = factor(data_source, levels = c("historical", "projected"))
  )

# ----- Build chart -----------------------------------------------------------

p_combined_energy <- combined_energy |>
  ggplot() +
  # Shaded background behind the projected period
  annotate("rect",
           xmin = 2026, xmax = Inf, ymin = -Inf, ymax = Inf,
           fill = "gray95") +
  # Stacked bars – same fill for both historical and projected
  geom_col(
    aes(x = financial_year,
        y = value_gwh,
        fill = reorder(coerced_tech_cat, -as.numeric(coerced_tech_cat))),
    position = "stack",
    width = 0.85
  ) +
  # Vertical divider at end of historical data
  geom_vline(xintercept = 2025.5,
             linetype = "dashed", colour = "gray50", linewidth = 0.6) +
  # Section labels
  annotate("text", x = 2017, y = Inf,
           label = "Historical actuals", vjust = 2,
           colour = "gray40", size = 3.2, fontface = "italic") +
  annotate("text", x = 2038, y = Inf,
           label = "ISP 2026 Draft\n(Step Change ODP)", vjust = 2,
           colour = "gray40", size = 3.2, fontface = "italic") +
  scale_fill_manual(
    values = setNames(util_table$colour_label, util_table$technology),
    na.value = "gray70"
  ) +
  scale_x_continuous(breaks = seq(2010, 2050, by = 5)) +
  scale_y_continuous(labels = label_comma()) +
  labs(
    title    = "NEM electricity generation: historical and projected",
    subtitle = "OpenNEM actuals (FY2010–FY2025) and ISP 2026 Draft Step Change ODP (FY2027–FY2050)",
    caption  = "Sources: OpenNEM; AEMO ISP 2026 Draft\nNote: FY2026 not present in either dataset",
    x        = "Financial year ending June",
    y        = "Energy (GWh)",
    fill     = "Technology"
  ) +
  theme_historical()

p_combined_energy


# ===== Data structure notes for Shiny integration =============================
#
# Key observations:
#
# 1. TEMPORAL ALIGNMENT
#    - Historical data: FY2009–FY2025 (monthly, aggregated to annual for charts)
#    - ISP projections: FY2025–FY2050 (5-year steps)
#    - Overlap year: FY2025 – use historical as "actuals", ISP as "projection start"
#
# 2. TECHNOLOGY MAPPING (OpenNEM → ISP)
#    The fueltech_lookup above maps OpenNEM codes to display labels.
#    For Shiny overlay, a crosswalk to ISP technology names is needed:
#
#    OpenNEM fueltech     → ISP technology (util_table)
#    ──────────────────────────────────────────────────
#    coal_black           → black coal
#    coal_brown           → brown coal
#    gas_ccgt             → mid-merit gas
#    gas_steam            → mid-merit gas (or peaking gas+liquids)
#    gas_ocgt             → flexible gas (or peaking gas+liquids)
#    gas_recip            → flexible gas
#    gas_wcmg             → flexible gas
#    distillate           → peaking gas+liquids
#    bioenergy_biomass    → biomass
#    hydro                → hydro
#    wind                 → wind
#    solar_utility        → utility-scale solar
#    solar_rooftop        → distributed pv
#    battery_discharging  → utility-scale storage
#    battery_charging     → utility storage load (negative)
#    pumps                → (no direct ISP equivalent – pumped hydro load)
#
# 3. UNIT CONVERSION
#    - OpenNEM energy: MWh → divide by 1,000 for GWh (matches ISP generation_output)
#    - OpenNEM power (metric="power"): sum of 5-min MW readings, NOT average MW.
#      To get avg MW: value / (days_in_month * 24 * 12)
#    - OpenNEM demand_energy: appears to be in GWh despite "MWh" unit label.
#    - demand_energy network_region parses as e.g. "energy_NSW1" – needs cleanup.
#
# 4. SHINY INTEGRATION OPTIONS
#    Option A: "Historical context" tab
#      - Standalone tab with historical-only charts (energy, emissions, price)
#      - Separate from ISP projections tabs
#      - Simplest to implement
#
#    Option B: Overlay on existing tabs
#      - Add historical actuals as shaded "actual" region on ISP projection charts
#      - Requires technology crosswalk and unit alignment
#      - More informative but more complex
#
#    Option C: Combined timeline chart
#      - x-axis spans FY2009 to FY2050
#      - Left portion = historical actuals, right = ISP projections
#      - Vertical dashed line at current year / ISP start year
#      - Most powerful for communicating trajectory
#
# 5. RECOMMENDED NEXT STEP
#    Create fueltech_to_isp_map lookup table (crosswalk) and test Option C
#    using a single region/scenario combination as a proof-of-concept.
#
################################################################################


# ===== Quick data structure inspection ========================================

glimpse(nem_historical_network_data)
glimpse(nem_historical_market_data)

# Unique fueltechs and metrics
nem_historical_network_data |> distinct(metric, unit, fueltech) |> arrange(metric, fueltech) |> print(n = 50)
nem_historical_market_data  |> distinct(metric, unit) |> print()

# Date range
nem_historical_network_data |>
  summarise(
    min_date = min(datetime),
    max_date = max(datetime),
    n_months = n_distinct(datetime)
  )
